name: Valuetogether - CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      빌드 시, 소스코드 컴파일이 진행되는데 이 때 필요한 JDK를 명시.
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

#       Gradle 빌드 시 사용할 명령어에 대해 권한을 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#       Gradle을 사용해 프로젝트 빌드를 수행
      - name: Build with Gradle
        run: ./gradlew build -x test

#       작성한 단위테스트가 있다면 테스트를 자동으로 수행
      - name: Test with Gradle
        run: SPRING_PROFILES_ACTIVE=[test] ./gradlew test

#       캐시액션으로 최적화
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
